# Generated by Django 6.0.3 on 2026-03-19 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('users', '0001_initial'),
        ('watchlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='user_profiles', to='subscription.usersubscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('watchlists', models.ManyToManyField(blank=True, related_name='user_profiles', to='watchlist.watchlist')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
