name: moiami
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "1234:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres