# Generated by Django 6.0.2 on 2026-05-18 20:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "movies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="watchlists",
                        to="catalog.movie",
                    ),
                ),
            ],
        ),
    ]
