# Generated by Django 6.0.2 on 2026-05-18 20:27

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.actions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieGetAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "happened_at",
                    models.BigIntegerField(
                        db_index=True,
                        default=apps.actions.models.current_timestamp,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="get_actions",
                        to="catalog.movie",
                    ),
                ),
            ],
        ),
    ]
