# Generated by Django 6.0.2 on 2026-05-18 20:27

import apps.catalog.models
import config.settings
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quality', models.CharField(choices=[('360', '360p'), ('1080', '1080p')], max_length=10)),
                ('file', models.FileField(blank=True, max_length=500, null=True, storage=config.settings.MinioVideoStorage(), upload_to=apps.catalog.models.video_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('script_writer', models.CharField(max_length=255)),
                ('age_restriction', models.IntegerField()),
                ('date', models.DateField()),
                ('date_of_premiere', models.DateField(blank=True, null=True)),
                ('country', models.CharField(max_length=255)),
                ('genres', models.ManyToManyField(related_name='movies', to='catalog.genre')),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.image')),
                ('subscriptions', models.ManyToManyField(related_name='movies', to='subscription.subscription')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.video')),
            ],
        ),
    ]
