# Generated by Django 6.0.2 on 2026-05-21 19:12

from django.db import migrations, models

import apps.catalog.models
import config.settings


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="link",
        ),
        migrations.AddField(
            model_name="image",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=config.settings.MinioPosterStorage(),
                upload_to=apps.catalog.models.poster_upload_path,
            ),
        ),
    ]
